import Head from 'next/head';
import Image from 'next/image';
import styles from './root.module.css';
import { ThemeProvider } from '@emotion/react';
import theme from '@/theme';

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>SociAlarm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="/background-pattern.png"
        alt="SociAlarm"
        className={styles.backgroundImage}
        fill
        quality={100}
      />
      <ThemeProvider theme={theme}>
        <main
          className={styles.main}
        >
          {children}
        </main>
      </ThemeProvider>
    </>
  );
};

export default RootLayout;
